name = "a2a-summary"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SUMMARIES"
id = "7c272519771640a2ba5ee5ccdc0131ab"
preview_id = "645a9d4192b94417ba46c485986fda68"

[[services]]
binding = "MCP_REGISTRY"
service = "a2a-mcp-registry"

[observability]
enabled = true

[[routes]]
pattern = "agent.summary.demos.build"
custom_domain = true

[vars]
ENVIRONMENT = "development"
AUTH_SCHEME = "none"