name = "a2a-air-tickets"
main = "src/index.ts"
compatibility_date = "2024-06-18"

[env.production]
name = "a2a-air-tickets"

[[kv_namespaces]]
binding = "BOOKINGS"
id = "b320e1be38d849e2a2453c0e06c37e68"
preview_id = "2743412349904df4bb14246cb7aacf80"

[ai]
binding = "AI"

[[services]]
binding = "MCP_REGISTRY"
service = "a2a-mcp-registry"
environment = "production"

[observability]
enabled = true

[[routes]]
pattern = "agent.air-tickets.demos.build"
custom_domain = true