name = "a2a-orchestrator"
main = "src/index.ts"
compatibility_date = "2024-06-18"

[env.production]
name = "a2a-orchestrator"

[[kv_namespaces]]
binding = "SESSIONS"
id = "30b704a797c44285bbebd48450168cfe"
preview_id = "e48a96092e124abca738de637fa1f019"

[ai]
binding = "AI"

[[services]]
binding = "MCP_REGISTRY"
service = "a2a-mcp-registry"

[[services]]
binding = "PLANNER"
service = "a2a-planner"

[[services]]
binding = "AIR_TICKETS"
service = "a2a-air-tickets"

[[services]]
binding = "HOTELS"
service = "a2a-hotels"

[[services]]
binding = "CAR_RENTAL"
service = "a2a-car-rental"

[observability]
enabled = true

[[routes]]
pattern = "agent.orchestrator.demos.build"
custom_domain = true