name = "a2a-hotels"
main = "src/index.ts"
compatibility_date = "2024-06-18"

[env.production]
name = "a2a-hotels"

[[kv_namespaces]]
binding = "BOOKINGS"
id = "de06a383a8ed440cbde8fa1d2ff6cb33"
preview_id = "2fad8c0c15594bdf829e5baceaa0e8e6"

[ai]
binding = "AI"

[[services]]
binding = "MCP_REGISTRY"
service = "a2a-mcp-registry"
environment = "production"

[observability]
enabled = true

[[routes]]
pattern = "agent.hotels.demos.build"
custom_domain = true